# netlify.toml

# production env
[context.production]
  command = "react-scripts build && mv build production"
  publish ="./production"

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://jonas-mika.herokuapp.com"
  REACT_APP_ENV = "PRO"
  CI=false

# dev env
[context.staging]
  command = "react-scripts build && mv build staging"
  publish = "./staging"

[context.staging.environment]
  REACT_APP_BACKEND_URL = "https://jonas-mika.herokuapp.com"
  REACT_APP_ENV = "STA"
  CI=false

# redirect all subroutes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
